name: build
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 16 * * 0' # sunday 16:00

jobs:
  quality_code:
    uses: nodecfdi/.github/.github/workflows/quality_code.yml@main

  tests:
    uses: nodecfdi/.github/.github/workflows/tests.yml@main
